version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=ap-northeast-1
      - SERVICES=s3,lambda,iam,dynamodb,stepfunctions
